# Generated by Django 3.2.9 on 2021-11-28 04:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('author', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='publisher',
            managers=[
                ('publisher', django.db.models.manager.Manager()),
            ],
        ),
    ]
