# Generated by Django 3.2.9 on 2021-12-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_student_studenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')])),
            ],
        ),
        migrations.AlterField(
            model_name='studenta',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshmana'), ('SO', 'Sophomorea'), ('JR', 'Juniora'), ('SR', 'Seniora'), ('GR', 'Graduatea')], default='FR', max_length=2),
        ),
    ]
