# Generated by Django 3.2.9 on 2021-12-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0004_auto_20211205_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cardno',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='SR', max_length=2),
        ),
    ]
