# Generated by Django 3.2.9 on 2021-12-06 07:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_choice_text'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('nowquestion', django.db.models.manager.Manager()),
            ],
        ),
    ]
